### ISSUE TITLE
Fix bug when building with Qthreads on AMD Threadripper platforms with full optimizations

### ISSUE THREAD

**Issue by jonathan-beard** [RaftLib/RaftLib#63]
Segfault at qthread init

```bash
Thread 3 "allocate" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5c58700 (LWP 33221)]
qthread_thread_new (team_leader=0, team=0x0, ret=0x0, arg_size=0, arg=0x7fffe8000b10, 
    f=0x555555578410 <pool_schedule::pool_run(void*)>) at qthread.c:2057
2057	    t->arg   = (void *)arg;
(gdb) bt
#0  qthread_thread_new (team_leader=0, team=0x0, ret=0x0, arg_size=0, arg=0x7fffe8000b10, 
    f=0x555555578410 <pool_schedule::pool_run(void*)>) at qthread.c:2057
#1  qthread_spawn (f=0x555555578410 <pool_schedule::pool_run(void*)>, arg=0x7fffe8000b10, 
    arg_size=0, ret=0x0, npreconds=0, preconds=0x0, target_shep=65535, feature_flag=0)
    at qthread.c:2634
#2  0x0000555555578b77 in pool_schedule::start() ()
#3  0x00007ffff76b70ff in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7bbd7fc in start_thread (arg=0x7ffff5c58700) at pthread_create.c:465
#5  0x00007ffff7118b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) q
A debugging session is active.
```

**Comment by jonathan-beard** [comment]
Fixed.
