### ISSUE TITLE
portexception, more than one port found

### ISSUE THREAD

**Issue by jonathan-beard** [RaftLib/RaftLib#88]
debugging new DSL parser....error message for splitop.cpp test case:

```bash
./splitop 
terminate called after throwing an instance of 'PortExceptionBase<3>'
  what():  One port expected, more than one found!
Output port from source kernel (raft::random_variate<std::linear_congruential_engine<unsigned long, 16807ul, 0ul, 2147483647ul>, std::uniform_int_distribution, unsigned int>) has more than a single port.
Aborted (core dumped)
```

**Comment by jonathan-beard** [comment]
More info:
```bash
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7bad535 in __GI_abort () at abort.c:79
#2  0x00007ffff7e26672 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7e322b6 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7e32301 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7e32535 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000055555555cac2 in MapBase::portNotFound(bool, PortExceptionBase<3> const&, raft::kernel*) [clone .cold] ()
#7  0x000055555555d64d in raft::parsemap::parse_link_helper(raft::kernel*, raft::kernel*) [clone .cold] ()
#8  0x000055555557eca0 in raft::parsemap::parse_link_split(raft::kernel*, raft::kernel*) ()
#9  0x000055555557c551 in operator<=(raft::kernel&, raft::kernel&) ()
#10 0x000055555555e9a2 in main ()
```

**Comment by jonathan-beard** [comment]
Fixed...moving on.
